# Generated by Django 5.2.8 on 2026-03-02 00:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('article_type', models.CharField(choices=[('howto', 'How-to'), ('procedure', 'Процедура/SOP'), ('policy', 'Политика'), ('troubleshooting', 'Траблшутинг'), ('faq', 'FAQ'), ('checklist', 'Чек-лист'), ('onboarding', 'Онбординг')], max_length=20, verbose_name='Тип статьи')),
                ('content_template', models.TextField(verbose_name='HTML-заготовка контента')),
                ('checklist', models.JSONField(blank=True, help_text='["Проверить битые ссылки", "Добавить alt к изображениям", ...]', null=True, verbose_name='Чек-лист качества')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон статьи',
                'verbose_name_plural': 'Шаблоны статей',
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержимое (HTML)')),
                ('variables', models.JSONField(blank=True, help_text='{"version": "2.5.1", "support_email": "help@bank.ru"}', null=True, verbose_name='Переменные')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сниппет',
                'verbose_name_plural': 'Сниппеты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('synonyms', models.JSONField(blank=True, help_text='["ДБО", "дистанционное банковское обслуживание"]', null=True, verbose_name='Синонимы/акронимы')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Использований')),
                ('is_controlled', models.BooleanField(default=False, verbose_name='Контролируемый словарь')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Содержимое (HTML)')),
                ('excerpt', models.TextField(blank=True, max_length=1000, verbose_name='Краткое описание')),
                ('article_type', models.CharField(choices=[('howto', 'How-to'), ('procedure', 'Процедура/SOP'), ('policy', 'Политика'), ('troubleshooting', 'Траблшутинг'), ('faq', 'FAQ'), ('checklist', 'Чек-лист'), ('onboarding', 'Онбординг')], default='howto', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На проверке'), ('published', 'Опубликовано'), ('needs_review', 'На пересмотре'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('needs_actualization', models.BooleanField(default=False, help_text='Авто-флаг при изменении связанного НПА', verbose_name='Требует актуализации')),
                ('review_period_months', models.PositiveSmallIntegerField(default=12, verbose_name='Период пересмотра (мес.)')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего пересмотра')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний пересмотр')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True, verbose_name='Поисковый вектор')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('avg_rating', models.FloatField(default=0, verbose_name='Средний рейтинг')),
                ('ratings_count', models.PositiveIntegerField(default=0, verbose_name='Количество оценок')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Комментариев')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('current_version', models.PositiveIntegerField(default=1, verbose_name='Текущая версия')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('editors', models.ManyToManyField(blank=True, related_name='kb_editable_articles', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы')),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_reviewed_articles', to=settings.AUTH_USER_MODEL, verbose_name='Пересмотрел')),
                ('related_documents', models.ManyToManyField(blank=True, related_name='kb_articles', to='documents.document', verbose_name='Связанные НПА')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.articletemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kb/attachments/%Y/%m/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='kb/thumbnails/', verbose_name='Миниатюра')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='knowledge.article', verbose_name='Статья')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='knowledge.article', verbose_name='Статья')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='knowledge.articlecomment', verbose_name='Ответ на')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (emoji/css)')),
                ('color', models.CharField(default='#CB11AB', max_length=7, verbose_name='Цвет')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Уровень вложенности')),
                ('path', models.CharField(blank=True, db_index=True, max_length=1000, verbose_name='Materialized Path')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_restricted', models.BooleanField(default=False, help_text='Видна только указанным подразделениям/ролям', verbose_name='Ограниченный доступ')),
                ('allowed_roles', models.JSONField(blank=True, help_text='["is_hr", "isModerator", ...]', null=True, verbose_name='Разрешённые роли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('allowed_departments', models.ManyToManyField(blank=True, related_name='kb_categories', to='org.department', verbose_name='Доступные подразделения')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.category', verbose_name='Родительская рубрика')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['path', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledge.category', verbose_name='Рубрика'),
        ),
        migrations.CreateModel(
            name='EditLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='Заблокировано')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_lock', to='knowledge.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
            ],
            options={
                'verbose_name': 'Блокировка редактирования',
                'verbose_name_plural': 'Блокировки редактирования',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ (HTML)')),
                ('helpful_yes', models.PositiveIntegerField(default=0, verbose_name='Помогло')),
                ('helpful_no', models.PositiveIntegerField(default=0, verbose_name='Не помогло')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='knowledge.category', verbose_name='Рубрика')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='knowledge.article', verbose_name='Полная статья')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='Запрос')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Результатов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on_create', models.BooleanField(default=True, verbose_name='При создании')),
                ('notify_on_update', models.BooleanField(default=True, verbose_name='При обновлении')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='knowledge.article', verbose_name='Статья')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='knowledge.category', verbose_name='Рубрика')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='knowledge.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='knowledge.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='1-5', verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='knowledge.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка статьи',
                'verbose_name_plural': 'Оценки статей',
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Описание изменений')),
                ('is_rollback', models.BooleanField(default=False, verbose_name='Откат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.article', verbose_name='Статья')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор правки')),
            ],
            options={
                'verbose_name': 'Версия статьи',
                'verbose_name_plural': 'Версии статей',
                'ordering': ['-version_number'],
                'unique_together': {('article', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Время на странице (сек)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to='knowledge.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['article', '-viewed_at'], name='knowledge_a_article_7845f7_idx'), models.Index(fields=['user', '-viewed_at'], name='knowledge_a_user_id_464ef1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path'], name='knowledge_c_path_4a1143_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='knowledge_c_parent__6abb06_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='knowledge_a_search__682520_gin'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='knowledge_a_status_66e656_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='knowledge_a_categor_44f19c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', '-created_at'], name='knowledge_a_author__67aaac_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_type', 'status'], name='knowledge_a_article_0c9d16_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['next_review_date'], name='knowledge_a_next_re_9282a4_idx'),
        ),
    ]
