# Generated by Django 5.2.8 on 2026-03-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Краткое описание'),
        ),
    ]
