# Generated by Django 5.2.8 on 2026-03-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_increase_excerpt_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Изменён'),
        ),
    ]
