# Generated by Django 5.2.8 on 2026-03-02 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_add_comment_is_edited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cross_articles', to='knowledge.category', verbose_name='Доп. рубрики (кросс-категории)'),
        ),
        migrations.CreateModel(
            name='SuggestedEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Предложенный заголовок')),
                ('content', models.TextField(verbose_name='Предложенный контент')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий к правке')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('review_comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_edits', to='knowledge.article', verbose_name='Статья')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_suggested_edits', to=settings.AUTH_USER_MODEL, verbose_name='Автор предложения')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_reviewed_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
            ],
            options={
                'verbose_name': 'Предложенная правка',
                'verbose_name_plural': 'Предложенные правки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='Термин')),
                ('description', models.TextField(blank=True, verbose_name='Описание / обоснование')),
                ('synonyms', models.CharField(blank=True, max_length=500, verbose_name='Синонимы')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Рассмотрено')),
                ('created_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.tag', verbose_name='Созданный тег')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_term_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_reviewed_terms', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
            ],
            options={
                'verbose_name': 'Заявка на термин',
                'verbose_name_plural': 'Заявки на термины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Просмотр'), ('download', 'Скачивание'), ('edit', 'Редактирование'), ('delete', 'Удаление'), ('publish', 'Публикация'), ('rollback', 'Откат версии')], max_length=20, verbose_name='Действие')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='knowledge.article', verbose_name='Статья')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', '-created_at'], name='knowledge_a_article_04df97_idx'), models.Index(fields=['user', '-created_at'], name='knowledge_a_user_id_5a12a7_idx'), models.Index(fields=['action', '-created_at'], name='knowledge_a_action_8121ec_idx')],
            },
        ),
    ]
