# Generated by Django 5.2.8 on 2026-01-23 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#CB11AB', max_length=7, verbose_name='Цвет')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('is_official', models.BooleanField(default=False, help_text='Официальные приказы, распоряжения', verbose_name='Официальная')),
                ('requires_moderation', models.BooleanField(default=True, verbose_name='Требует модерации')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Рубрика новостей',
                'verbose_name_plural': 'Рубрики новостей',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень вложенности')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыто модератором')),
                ('hidden_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина скрытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Запись изменения новости',
                'verbose_name_plural': 'Журнал изменений новостей',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Реакция на новость',
                'verbose_name_plural': 'Реакции на новости',
            },
        ),
        migrations.CreateModel(
            name='NewsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
            ],
            options={
                'verbose_name': 'Просмотр новости',
                'verbose_name_plural': 'Просмотры новостей',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_pinned', '-pin_order', '-published_at', '-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='Разрешить комментарии'),
        ),
        migrations.AddField(
            model_name='news',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество комментариев'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='news',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации'),
        ),
        migrations.AddField(
            model_name='news',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_news', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='news',
            name='moderation_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='news',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='approved', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.AddField(
            model_name='news',
            name='pin_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок закрепления'),
        ),
        migrations.AddField(
            model_name='news',
            name='pin_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закреплено до'),
        ),
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='news',
            name='schedule_publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланировать публикацию'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AddField(
            model_name='news',
            name='visibility',
            field=models.CharField(choices=[('all', 'Все сотрудники'), ('department', 'По подразделению'), ('selected', 'Выбранные сотрудники')], default='all', max_length=20, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='news',
            name='visible_to_departments',
            field=models.ManyToManyField(blank=True, related_name='visible_news', to='org.department', verbose_name='Доступно подразделениям'),
        ),
        migrations.AddField(
            model_name='news',
            name='visible_to_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_news', to=settings.AUTH_USER_MODEL, verbose_name='Доступно сотрудникам'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/%Y/%m/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news_attachments/%Y/%m/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('document', 'Документ'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='news_thumbnails/%Y/%m/', verbose_name='Превью')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Вложение новости',
                'verbose_name_plural': 'Вложения новостей',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='Рубрика'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-is_pinned', '-published_at'], name='news_news_is_pinn_3d06a5_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category', '-published_at'], name='news_news_categor_5d2cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['moderation_status', '-created_at'], name='news_news_moderat_2c02a9_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['author', '-created_at'], name='news_news_author__b96fec_idx'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_news_comments', to=settings.AUTH_USER_MODEL, verbose_name='Упоминания'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.newscomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AddField(
            model_name='newseditlog',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AddField(
            model_name='newseditlog',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='news.news', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='newsreaction',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='news.news', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='newsreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='newsview',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='news.news', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='newsview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='newscomment',
            index=models.Index(fields=['news', 'created_at'], name='news_newsco_news_id_a8077d_idx'),
        ),
        migrations.AddIndex(
            model_name='newscomment',
            index=models.Index(fields=['author', '-created_at'], name='news_newsco_author__ed67f1_idx'),
        ),
        migrations.AddIndex(
            model_name='newscomment',
            index=models.Index(fields=['parent', 'created_at'], name='news_newsco_parent__6a3dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='newsreaction',
            index=models.Index(fields=['news', 'emoji'], name='news_newsre_news_id_4d9e8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsreaction',
            unique_together={('news', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='newsview',
            index=models.Index(fields=['news', '-viewed_at'], name='news_newsvi_news_id_a2321d_idx'),
        ),
        migrations.AddIndex(
            model_name='newsview',
            index=models.Index(fields=['user', '-viewed_at'], name='news_newsvi_user_id_07016b_idx'),
        ),
    ]
