# Generated by Django 5.2.8 on 2026-01-23 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscategory_newscomment_newseditlog_newsreaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Обложка'),
        ),
        migrations.AlterUniqueTogether(
            name='newsreaction',
            unique_together={('news', 'user')},
        ),
    ]
