# Generated by Django 5.2.8 on 2026-01-23 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_ismoderator_alter_user_avatar'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Роль в проекте')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущий проект')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID в проектной системе')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('integration', 'Из проектной системы')], default='manual', max_length=20, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Проект сотрудника',
                'verbose_name_plural': 'Проекты сотрудников',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='user',
            name='archived_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина архивации'),
        ),
        migrations.AddField(
            model_name='user',
            name='band',
            field=models.CharField(blank=True, max_length=10, verbose_name='Грейд (Band)'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Категория сотрудника'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор из HR-системы', max_length=50, null=True, unique=True, verbose_name='ID сотрудника'),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёма'),
        ),
        migrations.AddField(
            model_name='user',
            name='hr_external_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные HR'),
        ),
        migrations.AddField(
            model_name='user',
            name='hr_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_employees', to=settings.AUTH_USER_MODEL, verbose_name='HR-партнёр'),
        ),
        migrations.AddField(
            model_name='user',
            name='hr_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация HR'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin_portal',
            field=models.BooleanField(default=False, verbose_name='Администратор портала'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивирован'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=False, verbose_name='HR-специалист'),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='office_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Расположение офиса'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Личный email'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Личный телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='org.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_birth_date',
            field=models.BooleanField(default=True, verbose_name='Показывать дату рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_personal_email',
            field=models.BooleanField(default=False, verbose_name='Показывать личный email'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_personal_phone',
            field=models.BooleanField(default=False, verbose_name='Показывать личный телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, null=True, verbose_name='Навыки и компетенции'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Работает'), ('vacation', 'В отпуске'), ('sick_leave', 'На больничном'), ('business_trip', 'В командировке'), ('maternity', 'В декрете'), ('unpaid_leave', 'Отпуск без содержания'), ('terminated', 'Уволен')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания статуса'),
        ),
        migrations.AddField(
            model_name='user',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituting_for', to=settings.AUTH_USER_MODEL, verbose_name='Замещающий'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Рабочий email'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Фото профиля'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='org.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isModerator',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='accounts_us_employe_0cbd94_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['birth_date'], name='accounts_us_birth_d_e9f7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='accounts_us_status_6bbe13_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'is_active'], name='accounts_us_departm_98cc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['manager'], name='accounts_us_manager_bb7da4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_archived'], name='accounts_us_is_arch_d49270_idx'),
        ),
        migrations.AddField(
            model_name='employeeproject',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
