# Generated by Django 5.2.8 on 2026-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeproject_alter_user_options_user_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_warnings',
            field=models.PositiveSmallIntegerField(default=0, help_text='После 3 предупреждений блокируется возможность комментирования', verbose_name='Предупреждения за комментарии'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments_banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки комментариев'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_comments_banned',
            field=models.BooleanField(default=False, help_text='Пользователь не может оставлять комментарии', verbose_name='Заблокирован для комментариев'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото профиля'),
        ),
    ]
