# Generated by Django 5.2.8 on 2026-01-23 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Уровень вложенности')),
                ('path', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Materialized Path')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID в 1С')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='org.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['path', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Новое значение')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('hr_sync', 'Синхронизация HR'), ('system', 'Системное'), ('api', 'Через API')], default='manual', max_length=20, verbose_name='Источник')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_changes', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись изменения сотрудника',
                'verbose_name_plural': 'Журнал изменений сотрудников',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Работает'), ('vacation', 'В отпуске'), ('sick_leave', 'На больничном'), ('business_trip', 'В командировке'), ('maternity', 'В декрете'), ('unpaid_leave', 'Отпуск без содержания'), ('terminated', 'Уволен')], max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_status_logs', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('substitute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituting_in_logs', to=settings.AUTH_USER_MODEL, verbose_name='Замещающий')),
            ],
            options={
                'verbose_name': 'Запись статуса сотрудника',
                'verbose_name_plural': 'Журнал статусов сотрудников',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Руководящая должность')),
                ('grade_min', models.CharField(blank=True, max_length=10, verbose_name='Минимальный грейд')),
                ('grade_max', models.CharField(blank=True, max_length=10, verbose_name='Максимальный грейд')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID в 1С')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='org.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['path'], name='org_departm_path_0b6a35_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent', 'is_active'], name='org_departm_parent__a6181f_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['external_id'], name='org_departm_externa_80661c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeechangelog',
            index=models.Index(fields=['employee', '-changed_at'], name='org_employe_employe_0b62db_idx'),
        ),
        migrations.AddIndex(
            model_name='employeechangelog',
            index=models.Index(fields=['field_name', '-changed_at'], name='org_employe_field_n_bb465a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeestatuslog',
            index=models.Index(fields=['employee', '-start_date'], name='org_employe_employe_3b8240_idx'),
        ),
        migrations.AddIndex(
            model_name='employeestatuslog',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='org_employe_status_ab3748_idx'),
        ),
    ]
