# Generated by Django 5.2.8 on 2026-01-23 13:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('document_type', models.CharField(choices=[('order', 'Приказ'), ('instruction', 'Указание'), ('regulation', 'Регламент'), ('policy', 'Политика'), ('letter', 'Письмо ЦБ'), ('memo', 'Служебная записка'), ('manual', 'Инструкция'), ('template', 'Шаблон'), ('other', 'Прочее')], max_length=20, verbose_name='Тип документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Дата вступления в силу')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата утраты силы')),
                ('basis', models.TextField(blank=True, help_text='На основании какого документа издан', verbose_name='Основание')),
                ('confidentiality', models.CharField(choices=[('public', 'Общедоступный'), ('internal', 'Для служебного пользования'), ('confidential', 'Конфиденциально'), ('secret', 'Секретно')], default='internal', max_length=20, verbose_name='Гриф конфиденциальности')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На согласовании'), ('active', 'Актуален'), ('outdated', 'Неактуален'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('tezis_link', models.URLField(blank=True, verbose_name='Ссылка в СЭД Тезис')),
                ('tezis_id', models.CharField(blank=True, max_length=100, verbose_name='ID в Тезис')),
                ('is_legal_hold', models.BooleanField(default=False, help_text='Заморозка удаления при проверках/расследованиях', verbose_name='Legal Hold')),
                ('legal_hold_reason', models.TextField(blank=True, verbose_name='Причина Legal Hold')),
                ('legal_hold_until', models.DateField(blank=True, null=True, verbose_name='Legal Hold до')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True, verbose_name='Поисковый вектор')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотров')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_documents', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_documents', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
                ('legal_hold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_holds', to=settings.AUTH_USER_MODEL, verbose_name='Legal Hold установил')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('retention_days', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для бессрочного хранения', null=True, verbose_name='Срок хранения (дней)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#CB11AB', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория документов',
                'verbose_name_plural': 'Категории документов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='Роль')),
                ('min_confidentiality', models.CharField(blank=True, choices=[('public', 'Общедоступный'), ('internal', 'Для служебного пользования'), ('confidential', 'Конфиденциально'), ('secret', 'Секретно')], max_length=20, verbose_name='Минимальный гриф')),
                ('can_view', models.BooleanField(default=False, verbose_name='Просмотр')),
                ('can_download', models.BooleanField(default=False, verbose_name='Скачивание')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Редактирование')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Удаление')),
                ('can_publish', models.BooleanField(default=False, verbose_name='Публикация')),
                ('can_manage_access', models.BooleanField(default=False, verbose_name='Управление доступом')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_rules', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_access_rules', to='org.department', verbose_name='Подразделение')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_access_rules', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='documents.documentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Правило доступа к документу',
                'verbose_name_plural': 'Правила доступа к документам',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла (байт)')),
                ('file_hash', models.CharField(max_length=64, verbose_name='SHA-256 хэш')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME тип')),
                ('is_scanned', models.BooleanField(default=False, verbose_name='Проверен антивирусом')),
                ('scan_result', models.CharField(choices=[('pending', 'Ожидает проверки'), ('clean', 'Чисто'), ('infected', 'Обнаружена угроза'), ('error', 'Ошибка проверки')], default='pending', max_length=20, verbose_name='Результат проверки')),
                ('scan_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('preview_file', models.FileField(blank=True, null=True, upload_to='previews/%Y/%m/', verbose_name='Превью (PDF)')),
                ('has_preview', models.BooleanField(default=False, verbose_name='Есть превью')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к версии')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Документ')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Версия документа',
                'verbose_name_plural': 'Версии документов',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True, verbose_name='Обязательно')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок ознакомления')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Ознакомлен')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Напоминание отправлено')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата напоминания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgements', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('acknowledged_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentversion', verbose_name='Версия ознакомления')),
            ],
            options={
                'verbose_name': 'Ознакомление с документом',
                'verbose_name_plural': 'Ознакомления с документами',
            },
        ),
        migrations.CreateModel(
            name='DocumentViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Просмотр документа',
                'verbose_name_plural': 'Журнал просмотров',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='documents_d_search__05a045_gin'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_number', 'document_date'], name='documents_d_documen_54b6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'document_type'], name='documents_d_status_ec1dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'status'], name='documents_d_categor_0ec696_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['confidentiality'], name='documents_d_confide_9faa37_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number__gt', '')), fields=('document_number', 'document_date'), name='unique_doc_number_date'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='documentacknowledgement',
            index=models.Index(fields=['user', 'acknowledged_at'], name='documents_d_user_id_94e8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacknowledgement',
            index=models.Index(fields=['document', 'required', 'acknowledged_at'], name='documents_d_documen_cbb365_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentacknowledgement',
            unique_together={('document', 'user')},
        ),
        migrations.AddIndex(
            model_name='documentviewlog',
            index=models.Index(fields=['document', '-viewed_at'], name='documents_d_documen_8f7d77_idx'),
        ),
        migrations.AddIndex(
            model_name='documentviewlog',
            index=models.Index(fields=['user', '-viewed_at'], name='documents_d_user_id_f5aa68_idx'),
        ),
    ]
