# Generated by Django 5.2.8 on 2026-03-10 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег опроса',
                'verbose_name_plural': 'Теги опросов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название опроса')),
                ('description', models.TextField(blank=True, verbose_name='Описание / цель')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('closed', 'Завершён'), ('archived', 'В архиве')], default='draft', max_length=16, verbose_name='Статус')),
                ('is_anonymous', models.BooleanField(default=False, help_text='При включении ответы не привязываются к сотруднику в интерфейсе.', verbose_name='Анонимный опрос')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='Разрешить повторное прохождение')),
                ('allow_edit_until_end', models.BooleanField(default=True, verbose_name='Разрешить изменять ответы до завершения')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало проведения')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание проведения')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое закрытие')),
                ('audience_type', models.CharField(choices=[('all', 'Весь банк'), ('departments', 'Подразделения'), ('users', 'Список сотрудников'), ('roles', 'Ролевые группы')], default='all', max_length=16, verbose_name='Целевая аудитория')),
                ('audience_roles', models.JSONField(blank=True, default=list, help_text='Список флагов пользователя, например: isModerator, is_hr.', verbose_name='Ролевые группы')),
                ('reminder_days', models.JSONField(blank=True, default=list, help_text='Например: [2, 1] — напомнить за 2 дня и за 1 день до окончания.', verbose_name='Напоминания (дни до окончания)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('audience_departments', models.ManyToManyField(blank=True, related_name='surveys', to='org.department', verbose_name='Подразделения')),
                ('audience_users', models.ManyToManyField(blank=True, related_name='targeted_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('excluded_users', models.ManyToManyField(blank=True, related_name='excluded_from_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Исключить сотрудников')),
                ('tags', models.ManyToManyField(blank=True, related_name='surveys', to='surveys.surveytag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.TextField(verbose_name='Текст вопроса')),
                ('help_text', models.TextField(blank=True, verbose_name='Пояснение')),
                ('question_type', models.CharField(choices=[('single_choice', 'Одиночный выбор'), ('multiple_choice', 'Множественный выбор'), ('scale', 'Шкала (1–10)'), ('free_text', 'Свободный текст')], default='single_choice', max_length=32, verbose_name='Тип вопроса')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('scale_min', models.IntegerField(default=1, verbose_name='Минимальное значение шкалы')),
                ('scale_max', models.IntegerField(default=10, verbose_name='Максимальное значение шкалы')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос опроса',
                'verbose_name_plural': 'Вопросы опросов',
                'ordering': ['survey', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.CharField(max_length=255, verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.surveyquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('last_step', models.PositiveIntegerField(default=0, help_text='Для восстановления прогресса', verbose_name='Последний шаг')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='Опрос')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ответ на опрос',
                'verbose_name_plural': 'Ответы на опросы',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, verbose_name='Текстовое значение')),
                ('value_number', models.FloatField(blank=True, null=True, verbose_name='Числовое значение')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyquestion', verbose_name='Вопрос')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey', 'user'], name='surveys_sur_survey__773590_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['question'], name='surveys_sur_questio_61b37a_idx'),
        ),
    ]
