# Generated by Django 5.2.8 on 2026-01-23 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('requires_confirmation', models.BooleanField(default=False, help_text='Например, подтверждение email', verbose_name='Требует подтверждения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Канал уведомлений',
                'verbose_name_plural': 'Каналы уведомлений',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=10, verbose_name='Приоритет')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения')),
                ('is_sent_email', models.BooleanField(default=False, verbose_name='Отправлено на email')),
                ('is_sent_push', models.BooleanField(default=False, verbose_name='Отправлено push')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('group_key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ключ группировки')),
                ('grouped_count', models.PositiveIntegerField(default=1, verbose_name='Количество в группе')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=20, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='Внешний ID')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel', verbose_name='Канал')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Запись доставки уведомления',
                'verbose_name_plural': 'Журнал доставки уведомлений',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Категория')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#CB11AB', max_length=7, verbose_name='Цвет')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=10, verbose_name='Приоритет по умолчанию')),
                ('title_template', models.CharField(help_text='Поддерживает {переменные}', max_length=255, verbose_name='Шаблон заголовка')),
                ('body_template', models.TextField(help_text='Поддерживает {переменные}', verbose_name='Шаблон текста')),
                ('email_template', models.TextField(blank=True, verbose_name='Шаблон email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('can_be_disabled', models.BooleanField(default=True, help_text='Может ли пользователь отключить этот тип уведомлений', verbose_name='Можно отключить')),
                ('group_similar', models.BooleanField(default=False, help_text='Группировать несколько однотипных уведомлений', verbose_name='Группировать похожие')),
                ('group_interval_minutes', models.PositiveIntegerField(default=60, verbose_name='Интервал группировки (минуты)')),
                ('default_channels', models.ManyToManyField(blank=True, to='notifications.notificationchannel', verbose_name='Каналы по умолчанию')),
            ],
            options={
                'verbose_name': 'Тип уведомления',
                'verbose_name_plural': 'Типы уведомлений',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationtype', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='В приложении')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push')),
                ('email_frequency', models.CharField(choices=[('instant', 'Мгновенно'), ('hourly', 'Раз в час'), ('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('never', 'Никогда')], default='instant', max_length=20, verbose_name='Частота email')),
                ('digest_time', models.TimeField(blank=True, null=True, verbose_name='Время дайджеста')),
                ('digest_day', models.PositiveSmallIntegerField(blank=True, help_text='0=Пн, 6=Вс', null=True, verbose_name='День недели для дайджеста')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='notifications.notificationtype', verbose_name='Тип уведомления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка уведомлений пользователя',
                'verbose_name_plural': 'Настройки уведомлений пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_c4ec61_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['group_key', '-created_at'], name='notificatio_group_k_c495c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationsettings',
            unique_together={('user', 'notification_type')},
        ),
    ]
